### ISSUE TITLE
What's the data source?

### ISSUE THREAD

**Issue by nitram509** [moodysalem/LatLongToTimezoneMaven#1]
Hi Moody,

this is an awesome peace of code.
What is the underlying data source, you use for all the geometries?
And how accurate are they?

Regards
Martin

**Comment by moodysalem** [comment]
This repository is just a maven project for https://github.com/drtimcooper/LatLongToTimezone

He describes how he generates the source data here
https://github.com/drtimcooper/LatLongToTimezone/blob/master/Documentation.txt
